### ISSUE TITLE
Position is not saved after exiting, every time I start it is top right.

### ISSUE THREAD

**Issue by Xebtria** [lemasato/POE-Trades-Companion#45]
position is always top right.

I move it to somewhere I want to have it, save options, it stays there. then I close it entirely and reopen, back top right.

super annoying, especially with clickthrough when inactive, where I can't move it, unless I go into options and disable clickthrough.

I am using window mode, not overlay, if that makes a difference. version 1.9.4

**Comment by Xebtria** [comment]
huh.

playing around in the options, checked something, unchecked something, generally just randomly clicked around, now it stays where I put it after restart. strange. closing this immediately again, but I will monitor the behaviour if it happens again.

**Comment by lemasato** [comment]
Could it be that you had the "Mode: Overlay" setting enabled?

**Comment by Xebtria** [comment]
nope, I played in the options, bot did not change the mode. and I had/have definitely mode:window.

**Comment by Xebtria** [comment]
Ok, so I started again today and it was back in top right. I move it again, close it, restart it, aaaand back in top right. Oh and it also didn't save the "click-through" setting I changed yesterday.... could it be that when I shut my pc down (which I do without closing all programs manually), then it kinda .... resets?

so let's find out if there is any trigger.

- changed the transparency setting while inactive, closed, restarted. It saved transparency, but reset the position.
- changed the transparency setting while inactive back to full, changed the transparency of active, closed, restarted. It saved transparency, **and also saved the position**
- again, changed the transparency setting while active back to full, changed the transparency of inactive again, closed, restarted. It saved transparency, and yet again also saved the position.
- to simulate the "I shut my pc down without closing it" I manually killed the exe via task manager and restarted, but it used the saved position and did not reset.

tried a few other settings as well, as of now, I can't make it reset the position again.
I'll reopen this for now, and keep monitoring, especially see what happens most likely tomorrow after work, but it looks like it resets "over night" for some weird reason I don't understand.

**Comment by lemasato** [comment]
The position is saved upon reloading or manually closing the script from the tray menu. This is why the save does not happen when shutting down the computer or killing the process. (Maybe I should make it so it is saved upon moving the GUI.)

>Oh and it also didn't save the "click-through" setting I changed yesterday

Are you sure about this one? These settings are only saved upon closing the Settings menu. Settings should not reset upon closing (or force killing) the process.

**Comment by Xebtria** [comment]
first of all, yes. I am sure about the click-through settings.

however, I noticed something. couple days ago my pc started making some problems, so while I boot I don't know what exactly happens, but sometimes my display crashes, I only get a small "banner" of artifacts instead of the actual boot display. so what I have to do is just hard shutdown the pc, immediately boot again, everything works fine. 

now it doesn't happen all the time, e.g. this morning it didn't happen, and this morning after boot the position of trades companion was the same as yesterday evening. but right now it happened again during boot, so I did again hard shutdown - reboot - and trades companion's position was again reset. 

this is **very** strange.

**Comment by lemasato** [comment]
A small banner of artifacts? Any picture of the issue?
Could be a faulty driver/cable/monitor/gpu. Could also be an HDD issue [Crystal Disk Info](http://crystalmark.info/download/index-e.html).
I'd recommend using [DDU](http://www.guru3d.com/files-details/display-driver-uninstaller-download.html) to make a clean uninstall of any display driver, then re-install.

It's completely expected behaviour to see the position being reset if the process was not closed normally. (Though it'll be fixed in next minor update).

**Comment by Xebtria** [comment]
yeah I know could be all kinds of things. gonna get a new graphics card tomorrow anyways (didn't order because of that) so after that I will know if the GPU was the issue :)

**Comment by lemasato** [comment]
1.9.5 released.
The position is now also saved upon dragging the interface.
Can we consider this issue fixed?

**Comment by Xebtria** [comment]
I didn't play for a few days, recently started again. currently version 1.9.8. behavior is still the same - after starting the pc again after I shut it down when the tool was still running, and then start tool again, tool still is on top right and not on the position it was before. 

sorry for late report but it looks for me it is still the same.

**Comment by lemasato** [comment]
Could you zip the logs folder (Documents\AutoHotkey\POE Trades Companion\Logs) and include it?

**Comment by Xebtria** [comment]
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/997491/Logs.zip)

**Comment by lemasato** [comment]
@Xebtria Have you encountered the issue since 1.9.9 release?

**Comment by Xebtria** [comment]
I haven't played for a week now but I started it up today and it looks like it works now :)
